language: python
# ===== Linux =====
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
matrix:
  fast_finish: true
  allow_failures:
    - python: 3.8
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
    - os: windows
  include: 
    # ======= OSX ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      script: python3 -m pytest -c pytest_osx.ini
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      script: python3 -m pytest -c pytest_osx.ini
    #  ====== WINDOWS =========
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - doskey python3=python
      script: python -m pytest
      after_success: python -m codecov
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows       # Windows 10.0.17134 N/A Build 17134
      language: shell   # 'language: python' is an error on Travis Windows
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
      install: pip3 install .
      after_success: python -m codecov
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows       # Windows 10.0.17134 N/A Build 17134
      language: shell   # 'language: python' is an error on Travis Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
      script: python -m pytest
      after_success: python -m codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install codecov
  - pip3 install --upgrade pip setuptools wheel
  - pip3 install --only-binary=all numpy scipy pandas scikit-learn nltk
install:
  - pip3 install ".[test,sklearn,nltk]"
script:
  - python3 -m pytest
after_success:
  - python3 -m codecov
